Repository Spiderpedia/WebLevelUp, pull requests merged in 2024-05, with the labels that each got.

#4 App is running on a single page
  Oauth/dashboard.html
  Oauth/login.html
  Oauth/oauthServer.js
  Oauth/server.js
  frontend/index.html
  frontend/styles.css
  package.json
Labels: enhancement

#6 Create deploy-to-EC2
  .github/workflows/deploy-to-EC2
Labels: enhancement

#5 nav bar is set app. just need to confirm that app.js is implemented c…
  Oauth/oauthServer.js
  frontend/app.js
  frontend/images/githubLogo.png
  frontend/images/spiderLogo.png
  frontend/index.html
  frontend/styles.css
Labels: enhancement

#16 Added a background image
  frontend/images/spider-web-background-free-vector.jpg
  frontend/index.html
  frontend/styles.css
Labels: enhancement

#19 multi OS support
  API/package-lock.json
  API/package.json
Labels: bug, enhancement

#20 URL fix
  API/index.js
Labels: bug

#25 removed console logs
  API/index.js
Labels: bug

#32 Frontend/oauth
  API/package-lock.json
  API/package.json
  frontend/app.js
  frontend/index.html
  frontend/styles.css
Labels: enhancement
